name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy-2.7 and pypy-3.8
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    outputs:
      version_changed: ${{ steps.check_file_changed.outputs.files_changed }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: set -o pipefail
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Build and install fluidfoam
        run: |
          cd ${{ github.workspace }} && make
      - name: Test fluidfoam
        run: make tests
      - name: Test fluidfoam coverage
        run: make tests_coverage
